kotlin.code.style=official
ktorVersion=2.3.12
kotlinVersion=2.0.0
kotlinTestVersion=2.0.0
kotlinLoggingVersion=7.0.0
slfj4Version=2.0.13
logbackVersion=1.5.6
conductorVersion=3.20.0
kspVersion=2.0.0-1.0.22
shadowJarVersion=8.0.0
kodeinVersion=7.22.0
kotlinxSerializationPluginVersion=2.0.0
kotlinxSerializationVersion=1.7.1
kotlinxCoroutineVersion=1.8.1
ktlintPluginVersion=12.1.1
kredsVersion=0.9.1
kdbcVersion=0.0.3
kotlinxDatetimeVersion=0.6.0
kotlinxUuidVersion=0.0.25
guavaVersion=33.2.1-jre
